[package]
name = "crayfish-vm3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
lto = true

[dependencies]
malachite = "0.4.4"
fxhash = "0.2.1"
